#define YY_parser_name_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from compilerC.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "compilerC.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

extern int linenum;
int yylex();
int search(char name[]);
void insert(char name[], int type, char value[]);
void printTab();
int yyerror(char *s);
void yyerror2(int type, char *s, char b[]);
void insertVal(char value[], int posi);
void valAssign(int modifier, char s1[], char s3[]);

struct symtab{
	char name[20];
	int type; // 1 is int, 2 is float, 3 for char , 4 for struct
	char value[20];
};

struct symtab tab[20];
int ptr = 0;


#line 40 "compilerC.y"
typedef union{
	char name[20];
    int int_val;

	struct strVariable{
		int intVar;
		float floatVar;
		char charVar;
	
	}variable;
	
	char str[200];
 
} yy_parser_name_stype;
#define YY_parser_name_STYPE yy_parser_name_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parser_name_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_name_BISON 1

#ifndef YY_parser_name_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_name_COMPATIBILITY 1
 #else
  #define  YY_parser_name_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_name_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_name_LTYPE
   #define YY_parser_name_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_name_STYPE 
   #define YY_parser_name_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_name_DEBUG
   #define  YY_parser_name_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_name_USE_GOTO
  #define YY_parser_name_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_name_USE_GOTO
 #define YY_parser_name_USE_GOTO 0
#endif

#ifndef YY_parser_name_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_name_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_name_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_name_DEBUG */
#endif


#ifndef YY_parser_name_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_name_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_name_LSP_NEEDED
#ifndef YY_parser_name_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_name_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_name_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_name_STYPE
#define YY_parser_name_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_name_PARSE
#define YY_parser_name_PARSE yyparse
#endif
#ifndef YY_parser_name_LEX
#define YY_parser_name_LEX yylex
#endif
#ifndef YY_parser_name_LVAL
#define YY_parser_name_LVAL yylval
#endif
#ifndef YY_parser_name_LLOC
#define YY_parser_name_LLOC yylloc
#endif
#ifndef YY_parser_name_CHAR
#define YY_parser_name_CHAR yychar
#endif
#ifndef YY_parser_name_NERRS
#define YY_parser_name_NERRS yynerrs
#endif
#ifndef YY_parser_name_DEBUG_FLAG
#define YY_parser_name_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_name_ERROR
#define YY_parser_name_ERROR yyerror
#endif

#ifndef YY_parser_name_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_name_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_name_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_name_PARSE_PARAM
  #define YY_parser_name_PARSE_PARAM void
 #endif
#endif

#if YY_parser_name_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_name_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_name_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_name_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_name_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_name_PURE
#  endif
#endif

#ifdef YY_parser_name_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_name_DEBUG 
#  endif
#endif

#ifndef YY_parser_name_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_name_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_name_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_name_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	TOK_SEMICOLON	258
#define	TOK_ADD	259
#define	TOK_SUB	260
#define	TOK_MUL	261
#define	TOK_DIV	262
#define	TOK_EQ	263
#define	TOK_INT	264
#define	TOK_FLOAT	265
#define	TOK_IDENT	266
#define	TOK_PRINTID	267
#define	TOK_MAIN	268
#define	TOK_CHA_DIR	269
#define	TOK_CHA_ESQ	270
#define	TOK_IDENT_ERR	271
#define	TOK_INCLUDE	272
#define	TOK_STRUCT	273
#define	TOK_WHILE	274
#define	TOK_FOR	275
#define	TOK_IF	276
#define	TOK_ELSE	277
#define	TOK_PAR_CUR_ESQ	278
#define	TOK_PAR_CUR_DIR	279
#define	TOK_LOWER_EQUAL	280
#define	TOK_GREATER_EQUAL	281
#define	TOK_EQUAL_EQUAL	282
#define	TOK_DIFERENT	283
#define	TOK_GREATER	284
#define	TOK_LOWER	285
#define	TOK_STR	286
#define	TOK_CHAR	287
#define	TOK_ONE_CHAR	288
#define	TOK_VOID	289
#define	TOK_UNDERSCORE	290
#define	TOK_NUM	291
#define	TOK_FNUM	292


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_name_CLASS
#define YY_parser_name_CLASS parser_name
#endif
#ifndef YY_parser_name_INHERIT
#define YY_parser_name_INHERIT
#endif
#ifndef YY_parser_name_MEMBERS
#define YY_parser_name_MEMBERS 
#endif
#ifndef YY_parser_name_LEX_BODY
#define YY_parser_name_LEX_BODY  
#endif
#ifndef YY_parser_name_ERROR_BODY
#define YY_parser_name_ERROR_BODY  
#endif
#ifndef YY_parser_name_CONSTRUCTOR_PARAM
#define YY_parser_name_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_name_CONSTRUCTOR_CODE
#define YY_parser_name_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_name_CONSTRUCTOR_INIT
#define YY_parser_name_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_name_USE_CONST_TOKEN
#define YY_parser_name_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_name_USE_CONST_TOKEN != 0
#ifndef YY_parser_name_ENUM_TOKEN
#define YY_parser_name_ENUM_TOKEN yy_parser_name_enum_token
#endif
#endif

class YY_parser_name_CLASS YY_parser_name_INHERIT
{
public: 
#if YY_parser_name_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int TOK_SEMICOLON;
static const int TOK_ADD;
static const int TOK_SUB;
static const int TOK_MUL;
static const int TOK_DIV;
static const int TOK_EQ;
static const int TOK_INT;
static const int TOK_FLOAT;
static const int TOK_IDENT;
static const int TOK_PRINTID;
static const int TOK_MAIN;
static const int TOK_CHA_DIR;
static const int TOK_CHA_ESQ;
static const int TOK_IDENT_ERR;
static const int TOK_INCLUDE;
static const int TOK_STRUCT;
static const int TOK_WHILE;
static const int TOK_FOR;
static const int TOK_IF;
static const int TOK_ELSE;
static const int TOK_PAR_CUR_ESQ;
static const int TOK_PAR_CUR_DIR;
static const int TOK_LOWER_EQUAL;
static const int TOK_GREATER_EQUAL;
static const int TOK_EQUAL_EQUAL;
static const int TOK_DIFERENT;
static const int TOK_GREATER;
static const int TOK_LOWER;
static const int TOK_STR;
static const int TOK_CHAR;
static const int TOK_ONE_CHAR;
static const int TOK_VOID;
static const int TOK_UNDERSCORE;
static const int TOK_NUM;
static const int TOK_FNUM;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_name_ENUM_TOKEN { YY_parser_name_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,TOK_SEMICOLON=258
	,TOK_ADD=259
	,TOK_SUB=260
	,TOK_MUL=261
	,TOK_DIV=262
	,TOK_EQ=263
	,TOK_INT=264
	,TOK_FLOAT=265
	,TOK_IDENT=266
	,TOK_PRINTID=267
	,TOK_MAIN=268
	,TOK_CHA_DIR=269
	,TOK_CHA_ESQ=270
	,TOK_IDENT_ERR=271
	,TOK_INCLUDE=272
	,TOK_STRUCT=273
	,TOK_WHILE=274
	,TOK_FOR=275
	,TOK_IF=276
	,TOK_ELSE=277
	,TOK_PAR_CUR_ESQ=278
	,TOK_PAR_CUR_DIR=279
	,TOK_LOWER_EQUAL=280
	,TOK_GREATER_EQUAL=281
	,TOK_EQUAL_EQUAL=282
	,TOK_DIFERENT=283
	,TOK_GREATER=284
	,TOK_LOWER=285
	,TOK_STR=286
	,TOK_CHAR=287
	,TOK_ONE_CHAR=288
	,TOK_VOID=289
	,TOK_UNDERSCORE=290
	,TOK_NUM=291
	,TOK_FNUM=292


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_name_PARSE (YY_parser_name_PARSE_PARAM);
 virtual void YY_parser_name_ERROR(char *msg) YY_parser_name_ERROR_BODY;
#ifdef YY_parser_name_PURE
#ifdef YY_parser_name_LSP_NEEDED
 virtual int  YY_parser_name_LEX (YY_parser_name_STYPE *YY_parser_name_LVAL,YY_parser_name_LTYPE *YY_parser_name_LLOC) YY_parser_name_LEX_BODY;
#else
 virtual int  YY_parser_name_LEX (YY_parser_name_STYPE *YY_parser_name_LVAL) YY_parser_name_LEX_BODY;
#endif
#else
 virtual int YY_parser_name_LEX() YY_parser_name_LEX_BODY;
 YY_parser_name_STYPE YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
 YY_parser_name_LTYPE YY_parser_name_LLOC;
#endif
 int   YY_parser_name_NERRS;
 int    YY_parser_name_CHAR;
#endif
#if YY_parser_name_DEBUG != 0
 int YY_parser_name_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_name_CLASS(YY_parser_name_CONSTRUCTOR_PARAM);
public:
 YY_parser_name_MEMBERS 
};
/* other declare folow */
#if YY_parser_name_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_name_CLASS::TOK_SEMICOLON=258;
const int YY_parser_name_CLASS::TOK_ADD=259;
const int YY_parser_name_CLASS::TOK_SUB=260;
const int YY_parser_name_CLASS::TOK_MUL=261;
const int YY_parser_name_CLASS::TOK_DIV=262;
const int YY_parser_name_CLASS::TOK_EQ=263;
const int YY_parser_name_CLASS::TOK_INT=264;
const int YY_parser_name_CLASS::TOK_FLOAT=265;
const int YY_parser_name_CLASS::TOK_IDENT=266;
const int YY_parser_name_CLASS::TOK_PRINTID=267;
const int YY_parser_name_CLASS::TOK_MAIN=268;
const int YY_parser_name_CLASS::TOK_CHA_DIR=269;
const int YY_parser_name_CLASS::TOK_CHA_ESQ=270;
const int YY_parser_name_CLASS::TOK_IDENT_ERR=271;
const int YY_parser_name_CLASS::TOK_INCLUDE=272;
const int YY_parser_name_CLASS::TOK_STRUCT=273;
const int YY_parser_name_CLASS::TOK_WHILE=274;
const int YY_parser_name_CLASS::TOK_FOR=275;
const int YY_parser_name_CLASS::TOK_IF=276;
const int YY_parser_name_CLASS::TOK_ELSE=277;
const int YY_parser_name_CLASS::TOK_PAR_CUR_ESQ=278;
const int YY_parser_name_CLASS::TOK_PAR_CUR_DIR=279;
const int YY_parser_name_CLASS::TOK_LOWER_EQUAL=280;
const int YY_parser_name_CLASS::TOK_GREATER_EQUAL=281;
const int YY_parser_name_CLASS::TOK_EQUAL_EQUAL=282;
const int YY_parser_name_CLASS::TOK_DIFERENT=283;
const int YY_parser_name_CLASS::TOK_GREATER=284;
const int YY_parser_name_CLASS::TOK_LOWER=285;
const int YY_parser_name_CLASS::TOK_STR=286;
const int YY_parser_name_CLASS::TOK_CHAR=287;
const int YY_parser_name_CLASS::TOK_ONE_CHAR=288;
const int YY_parser_name_CLASS::TOK_VOID=289;
const int YY_parser_name_CLASS::TOK_UNDERSCORE=290;
const int YY_parser_name_CLASS::TOK_NUM=291;
const int YY_parser_name_CLASS::TOK_FNUM=292;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_name_CLASS::token */
#endif
/*apres const  */
YY_parser_name_CLASS::YY_parser_name_CLASS(YY_parser_name_CONSTRUCTOR_PARAM) YY_parser_name_CONSTRUCTOR_INIT
{
#if YY_parser_name_DEBUG != 0
YY_parser_name_DEBUG_FLAG=0;
#endif
YY_parser_name_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		131
#define	YYFLAG		-32768
#define	YYNTBASE	38

#define YYTRANSLATE(x) ((unsigned)(x) <= 292 ? yytranslate[x] : 53)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37
};

#if YY_parser_name_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,    10,    17,    23,    29,    30,    31,
    35,    38,    42,    43,    47,    50,    53,    56,    59,    62,
    65,    66,    68,    70,    72,    80,    88,   100,   116,   132,
   136,   140,   144,   148,   152,   156,   160,   164,   169,   176,
   181,   185,   189,   193,   197,   199,   201,   203
};

static const short yyrhs[] = {    39,
     0,    17,    38,     0,    41,     0,    40,    39,     0,    18,
    14,    43,    15,    11,     3,     0,    34,    13,    14,    42,
    15,     0,     9,    13,    14,    42,    15,     0,     0,     0,
    50,     3,    42,     0,    45,    42,     0,    44,     3,    42,
     0,     0,    44,     3,    43,     0,     9,    11,     0,     9,
    16,     0,    10,    11,     0,    10,    16,     0,    32,    11,
     0,    32,    16,     0,     0,    46,     0,    47,     0,    48,
     0,    19,    23,    49,    24,    14,    42,    15,     0,    21,
    23,    49,    24,    14,    42,    15,     0,    21,    23,    49,
    24,    14,    42,    15,    22,    14,    42,    15,     0,    20,
    23,    11,     8,    11,     3,    49,     3,    11,     4,     4,
    24,    14,    42,    15,     0,    20,    23,    11,     8,    36,
     3,    49,     3,    11,     4,     4,    24,    14,    42,    15,
     0,    11,    28,    51,     0,    11,    27,    51,     0,    11,
    25,    51,     0,    11,    30,    51,     0,    11,    26,    51,
     0,    11,    29,    51,     0,    11,     8,    51,     0,    11,
     8,    33,     0,    12,    23,    11,    24,     0,    12,    23,
    35,    51,    35,    24,     0,    12,    23,    31,    24,     0,
    51,     4,    51,     0,    51,     7,    51,     0,    51,     5,
    51,     0,    51,     6,    51,     0,    11,     0,    52,     0,
    36,     0,    37,     0
};

#endif

#if (YY_parser_name_DEBUG != 0) || defined(YY_parser_name_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    63,    63,    65,    65,    67,    82,    83,    85,    91,    92,
    93,    94,    97,    98,   100,   115,   121,   135,   140,   154,
   159,   161,   161,   161,   163,   165,   167,   172,   177,   184,
   217,   250,   282,   314,   346,   380,   397,   413,   427,   438,
   445,   465,   484,   503,   523,   547,   550,   555
};

static const char * const yytname[] = {   "$","error","$illegal.","TOK_SEMICOLON",
"TOK_ADD","TOK_SUB","TOK_MUL","TOK_DIV","TOK_EQ","TOK_INT","TOK_FLOAT","TOK_IDENT",
"TOK_PRINTID","TOK_MAIN","TOK_CHA_DIR","TOK_CHA_ESQ","TOK_IDENT_ERR","TOK_INCLUDE",
"TOK_STRUCT","TOK_WHILE","TOK_FOR","TOK_IF","TOK_ELSE","TOK_PAR_CUR_ESQ","TOK_PAR_CUR_DIR",
"TOK_LOWER_EQUAL","TOK_GREATER_EQUAL","TOK_EQUAL_EQUAL","TOK_DIFERENT","TOK_GREATER",
"TOK_LOWER","TOK_STR","TOK_CHAR","TOK_ONE_CHAR","TOK_VOID","TOK_UNDERSCORE",
"TOK_NUM","TOK_FNUM","prog","struct","structdefs","main","stmts","vardefs","vardef",
"ciclesAndOther","whileCicle","ifCond","forCicle","exprBol","stmt","expr","RAW",
""
};
#endif

static const short yyr1[] = {     0,
    38,    38,    39,    39,    40,    41,    41,    41,    42,    42,
    42,    42,    43,    43,    44,    44,    44,    44,    44,    44,
    44,    45,    45,    45,    46,    47,    47,    48,    48,    49,
    49,    49,    49,    49,    49,    50,    50,    50,    50,    50,
    51,    51,    51,    51,    51,    51,    52,    52
};

static const short yyr2[] = {     0,
     1,     2,     1,     2,     6,     5,     5,     0,     0,     3,
     2,     3,     0,     3,     2,     2,     2,     2,     2,     2,
     0,     1,     1,     1,     7,     7,    11,    15,    15,     3,
     3,     3,     3,     3,     3,     3,     3,     4,     6,     4,
     3,     3,     3,     3,     1,     1,     1,     1
};

static const short yydefact[] = {     8,
     0,     8,     0,     0,     1,     8,     3,     0,     2,    13,
     0,     4,     9,     0,     0,     0,     0,     0,     9,     0,
     0,     0,     0,     0,     0,     0,     9,    22,    23,    24,
     0,    15,    16,    17,    18,    19,    20,     0,    13,     0,
     0,     0,     0,     0,     0,     7,     9,    11,     9,     0,
    14,     6,    45,    37,    47,    48,    36,    46,     0,     0,
     0,     0,     0,     0,     0,    12,    10,     5,     0,     0,
     0,     0,    38,    40,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    41,    43,    44,    42,     0,    32,
    34,    31,    30,    35,    33,     9,     0,     0,     9,    39,
     0,     0,     0,     0,    25,     0,     0,    26,     0,     0,
     0,     0,     0,     9,     0,     0,     0,     0,     0,    27,
     0,     0,     9,     9,     0,     0,    28,    29,     0,     0,
     0
};

static const short yydefgoto[] = {     9,
     5,     6,     7,    25,    17,    26,    27,    28,    29,    30,
    63,    31,    57,    58
};

static const short yypact[] = {     9,
    -4,     9,     6,    25,-32768,    16,-32768,    26,-32768,     7,
    28,-32768,     3,    21,    37,    62,    34,    61,     3,    57,
   -12,    43,    51,    52,    64,    73,     3,-32768,-32768,-32768,
    88,-32768,-32768,-32768,-32768,-32768,-32768,    81,     7,    78,
     8,    20,    85,    86,    85,-32768,     3,-32768,     3,    91,
-32768,-32768,-32768,-32768,-32768,-32768,    83,-32768,    74,    75,
    10,    56,    76,    93,    79,-32768,-32768,-32768,    10,    10,
    10,    10,-32768,-32768,    -2,    10,    10,    10,    10,    10,
    10,    92,    18,    94,    50,    50,-32768,-32768,    87,    83,
    83,    83,    83,    83,    83,     3,    99,   104,     3,-32768,
    95,    85,    85,    97,-32768,   106,   110,    96,   103,   105,
   101,   113,   115,     3,   116,   117,   107,   100,   102,-32768,
   109,   111,     3,     3,   112,   114,-32768,-32768,   128,   130,
-32768
};

static const short yypgoto[] = {   131,
   126,-32768,-32768,   -19,    98,    -3,-32768,-32768,-32768,-32768,
   -44,-32768,    -9,-32768
};


#define	YYLAST		137


static const short yytable[] = {    40,
    65,    69,    70,    71,    72,   -21,    18,    48,     8,   -21,
    42,    14,    15,    20,    21,    14,    15,     1,    53,    10,
    53,    22,    23,    24,     1,     2,     3,    66,    97,    67,
    59,    32,    89,     3,    16,    18,    33,    11,    16,    13,
    54,    19,     4,    55,    56,    55,    56,    34,    38,     4,
    60,    75,    35,    98,    61,    71,    72,   106,   107,    85,
    86,    87,    88,    39,    41,    43,    90,    91,    92,    93,
    94,    95,    36,    44,    45,    47,   101,    37,    46,   104,
    76,    77,    78,    79,    80,    81,    69,    70,    71,    72,
    49,    50,    52,    68,   117,    62,    64,    73,    74,    82,
    83,   102,    84,   125,   126,    96,   103,    99,   109,   105,
   100,   108,   110,   112,   114,   113,   115,   111,   116,   118,
   119,   120,   123,   121,   124,   122,   127,   130,   128,   131,
   129,    12,     0,     0,     0,     0,    51
};

static const short yycheck[] = {    19,
    45,     4,     5,     6,     7,     3,    10,    27,    13,     3,
    23,     9,    10,    11,    12,     9,    10,     9,    11,    14,
    11,    19,    20,    21,     9,    17,    18,    47,    11,    49,
    11,    11,    35,    18,    32,    39,    16,    13,    32,    14,
    33,    14,    34,    36,    37,    36,    37,    11,    15,    34,
    31,    61,    16,    36,    35,     6,     7,   102,   103,    69,
    70,    71,    72,     3,     8,    23,    76,    77,    78,    79,
    80,    81,    11,    23,    23,     3,    96,    16,    15,    99,
    25,    26,    27,    28,    29,    30,     4,     5,     6,     7,
     3,    11,    15,     3,   114,    11,    11,    24,    24,    24,
     8,     3,    24,   123,   124,    14,     3,    14,     3,    15,
    24,    15,     3,    11,    14,    11,     4,    22,     4,     4,
     4,    15,    14,    24,    14,    24,    15,     0,    15,     0,
     0,     6,    -1,    -1,    -1,    -1,    39
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_name_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_name_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_name_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_name_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_name_CHAR = (token), YY_parser_name_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_name_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_name_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_name_PURE
/* UNPURE */
#define YYLEX           YY_parser_name_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_name_CHAR;                      /*  the lookahead symbol        */
YY_parser_name_STYPE      YY_parser_name_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_name_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_name_LSP_NEEDED
YY_parser_name_LTYPE YY_parser_name_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_name_LSP_NEEDED
#define YYLEX           YY_parser_name_LEX(&YY_parser_name_LVAL, &YY_parser_name_LLOC)
#else
#define YYLEX           YY_parser_name_LEX(&YY_parser_name_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_name_DEBUG != 0
int YY_parser_name_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_name_CLASS::
#endif
     YY_parser_name_PARSE(YY_parser_name_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_name_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_name_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_name_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_name_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_name_LSP_NEEDED
  YY_parser_name_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_name_LTYPE *yyls = yylsa;
  YY_parser_name_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_name_PURE
  int YY_parser_name_CHAR;
  YY_parser_name_STYPE YY_parser_name_LVAL;
  int YY_parser_name_NERRS;
#ifdef YY_parser_name_LSP_NEEDED
  YY_parser_name_LTYPE YY_parser_name_LLOC;
#endif
#endif

  YY_parser_name_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_name_NERRS = 0;
  YY_parser_name_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_name_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_name_LSP_NEEDED
      YY_parser_name_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_name_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_name_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_name_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_name_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_name_LSP_NEEDED
      yyls = (YY_parser_name_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_name_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_name_CHAR == YYEMPTY)
    {
#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_name_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_name_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_name_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_name_CHAR);

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_name_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_name_CHAR, YY_parser_name_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_name_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_name_CHAR != YYEOF)
    YY_parser_name_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
  *++yylsp = YY_parser_name_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 5:
#line 67 "compilerC.y"
{
		
		int flag;
		char *t;
	    flag = search(yyvsp[-1].name);

		if(flag == -1){
			insert(yyvsp[-1].name, 4, "0");
		}else{
			t = "Struct identifier already defined - ";
			yyerror2(3,t, yyvsp[-1].name);
		}									
											
	;
    break;}
case 8:
#line 86 "compilerC.y"
{
		char *t ="Parsing Error";
		yyerror2(3,t,"");
	;
    break;}
case 15:
#line 101 "compilerC.y"
{

	    int flag;
		char *t;
	    flag = search(yyvsp[0].name);

		if(flag == -1){
			insert(yyvsp[0].name, 1, "0");
		}else{
			t = "Identifier already defined - ";
			yyerror2(3,t, yyvsp[0].name);
		}

	  ;
    break;}
case 16:
#line 116 "compilerC.y"
{
		char *t ="Invalid Identifier - ";
		yyerror2(3,t,yyvsp[0].name);
	  ;
    break;}
case 17:
#line 121 "compilerC.y"
{

	    int flag;
		char *t;
	    flag = search(yyvsp[0].name);

		if(flag == -1){
			insert(yyvsp[0].name, 2, "0.0");
		}else{
			t = "Identifier already defined - ";
			yyerror2(3,t,yyvsp[0].name);
		}

	  ;
    break;}
case 18:
#line 136 "compilerC.y"
{
		char *t ="Invalid Identifier - ";
		yyerror2(3,t,yyvsp[0].name);
	  ;
    break;}
case 19:
#line 141 "compilerC.y"
{
	    int flag;
		char *t;
	    flag = search(yyvsp[0].name);

		if(flag == -1){
			insert(yyvsp[0].name, 3, " ");
		}else{
			t = "Identifier already defined - ";
			yyerror2(3,t,yyvsp[0].name);
		}

	;
    break;}
case 20:
#line 155 "compilerC.y"
{
		char *t ="Invalid Identifier - ";
		yyerror2(3,t,yyvsp[0].name);
	  ;
    break;}
case 30:
#line 185 "compilerC.y"
{
		int flag;
		char *t;
		int type;
	    flag = search(yyvsp[-2].name);
		struct strVariable temp2;
		
		temp2.floatVar=0.0;
		temp2.charVar=' ';
		
		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(3,t,yyvsp[-2].name);
		}else{
			type=tab[flag].type;
			
			if(type==1){ // int var
				if( atoi(tab[flag].value) != yyvsp[0].variable.intVar){
					temp2.intVar = 1; // printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1;  //  printf("%d\n",temp2.intVar);
				}
			} else if (type==2){ // float var
				if( atof(tab[flag].value) != yyvsp[0].variable.floatVar){
					temp2.intVar = 1;  // printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1;  // printf("%d\n",temp2.intVar);
				}
			}
			yyval.variable = temp2;
		}
	  ;
    break;}
case 31:
#line 218 "compilerC.y"
{
		int flag;
		char *t;
		int type;
	    flag = search(yyvsp[-2].name);
		struct strVariable temp2;
		
		temp2.floatVar=0.0;
		temp2.charVar=' ';
		
		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(3,t,yyvsp[-2].name);
		}else{
			type=tab[flag].type;
			
			if(type==1){ // int var
				if( atoi(tab[flag].value) == yyvsp[0].variable.intVar){
					temp2.intVar = 1; // printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1;  //  printf("%d\n",temp2.intVar);
				}
			} else if (type==2){ // float var
				if( atof(tab[flag].value) == yyvsp[0].variable.floatVar){
					temp2.intVar = 1;  // printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1;  // printf("%d\n",temp2.intVar);
				}
			}
			yyval.variable = temp2;
		}
	  ;
    break;}
case 32:
#line 250 "compilerC.y"
{
		int flag;
		char *t;
		int type;
	    flag = search(yyvsp[-2].name);
		struct strVariable temp2;
		
		temp2.floatVar=0.0;
		temp2.charVar=' ';
		
		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(1,t,yyvsp[-2].name);
		}else{
			type=tab[flag].type;
			
			if(type==1){ // int var
				if( atoi(tab[flag].value) <= yyvsp[0].variable.intVar){
					temp2.intVar = 1; //  printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			} else if (type==2){ // float var
				if( atof(tab[flag].value) <= yyvsp[0].variable.floatVar){
					temp2.intVar = 1; //  printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1;  // printf("%d\n",temp2.intVar);
				}
			}
			yyval.variable = temp2;
		}
	  ;
    break;}
case 33:
#line 282 "compilerC.y"
{
		int flag;
		char *t;
		int type;
	    flag = search(yyvsp[-2].name);
		struct strVariable temp2;
		
		temp2.floatVar=0.0;
		temp2.charVar=' ';
		
		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(1,t,yyvsp[-2].name);
		}else{
			type=tab[flag].type;
			
			if(type==1){ // int var
				if( atoi(tab[flag].value) < yyvsp[0].variable.intVar){
					temp2.intVar = 1; //  printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			} else if (type==2){ // float var
				if( atof(tab[flag].value) < yyvsp[0].variable.floatVar){
					temp2.intVar = 1; //  printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			}
			yyval.variable = temp2;
		}
	  ;
    break;}
case 34:
#line 314 "compilerC.y"
{
		int flag;
		char *t;
		int type;
	    flag = search(yyvsp[-2].name);
		struct strVariable temp2;
		
		temp2.floatVar=0.0;
		temp2.charVar=' ';
		
		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(1,t,yyvsp[-2].name);
		}else{
			type=tab[flag].type;
			
			if(type==1){ // int var
				if( atoi(tab[flag].value) >= yyvsp[0].variable.intVar){
					temp2.intVar = 1;  // printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			} else if (type==2){ // float var
				if( atof(tab[flag].value) >= yyvsp[0].variable.floatVar){
					temp2.intVar = 1; // printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			}
			yyval.variable = temp2;
		}
	  ;
    break;}
case 35:
#line 346 "compilerC.y"
{
		int flag;
		char *t;
		int type;
	    flag = search(yyvsp[-2].name);
		struct strVariable temp2;
		
		temp2.floatVar=0.0;
		temp2.charVar=' ';
		
		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(1,t,yyvsp[-2].name);
		}else{
			type=tab[flag].type;
			
			if(type==1){ // int var
				if( atoi(tab[flag].value) > yyvsp[0].variable.intVar){
					temp2.intVar = 1; //  printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			} else if (type==2){ // float var
				if( atof(tab[flag].value) > yyvsp[0].variable.floatVar){
					temp2.intVar = 1; //  printf("%d\n",temp2.intVar);
				}else{
					temp2.intVar = -1; //  printf("%d\n",temp2.intVar);
				}
			}
			yyval.variable = temp2;
		}
	  ;
    break;}
case 36:
#line 382 "compilerC.y"
{
		int modifier;
		char val[15];
		if(yyvsp[0].variable.intVar != 0) {
			modifier = 1;
			sprintf(val, "%d", yyvsp[0].variable.intVar);
		}else if(yyvsp[0].variable.floatVar != 0){
			modifier = 2;
			sprintf(val, "%f", yyvsp[0].variable.floatVar);
		} else if (yyvsp[0].variable.charVar != ' '){
			modifier = 3;
			sprintf(val, "%c", yyvsp[0].variable.charVar);
		}
		valAssign(modifier, yyvsp[-2].name, val);
	  ;
    break;}
case 37:
#line 398 "compilerC.y"
{
		int modifier;
		char val[15];
		if(yyvsp[0].variable.intVar != 0) {
			modifier = 1;
			sprintf(val, "%d", yyvsp[0].variable.intVar);
		}else if(yyvsp[0].variable.floatVar != 0){
			modifier = 2;
			sprintf(val, "%f", yyvsp[0].variable.floatVar);
		} else if (yyvsp[0].variable.charVar != ' '){
			modifier = 3;
			sprintf(val, "%c", yyvsp[0].variable.charVar);
		}
		valAssign(modifier, yyvsp[-2].name, val);
	;
    break;}
case 38:
#line 414 "compilerC.y"
{
		//todo change print to file
		int flag;
		char *t;
	    flag = search(yyvsp[-1].name);

		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(3,t, yyvsp[-1].name);
		}else{
			printf("%s\n", tab[flag].value);
		}
	  ;
    break;}
case 39:
#line 429 "compilerC.y"
{
		if(yyvsp[-2].variable.intVar != 0){
			printf("%d\n", yyvsp[-2].variable.intVar);
		} else if (yyvsp[-2].variable.charVar != ' ' ) {
			printf("%c\n", yyvsp[-2].variable.charVar);
		} else {
			printf("%f\n", yyvsp[-2].variable.floatVar);
		} 
	;
    break;}
case 40:
#line 439 "compilerC.y"
{
		printf("%s\n",yyvsp[-1].str);
	;
    break;}
case 41:
#line 447 "compilerC.y"
{
		struct strVariable temp2;

		int flag;
		if(yyvsp[-2].variable.intVar != 0 && yyvsp[0].variable.intVar != 0) {
			temp2.floatVar = 0;
			temp2.intVar = yyvsp[-2].variable.intVar + yyvsp[0].variable.intVar;
		}else if(yyvsp[-2].variable.floatVar != 0 && yyvsp[0].variable.floatVar != 0) {
			temp2.intVar = 0;
			temp2.floatVar = yyvsp[-2].variable.floatVar + yyvsp[0].variable.floatVar;
		}else {
			char *t = "Type mismatch";
			yyerror2(3,t, "");
		}
		
		yyval.variable = temp2;

	  ;
    break;}
case 42:
#line 467 "compilerC.y"
{
		struct strVariable temp;

		int flag;
		if(yyvsp[-2].variable.intVar != 0 && yyvsp[0].variable.intVar != 0) {
			temp.floatVar = 0;
			temp.intVar = yyvsp[-2].variable.intVar / yyvsp[0].variable.intVar;
		}else if(yyvsp[-2].variable.floatVar != 0 && yyvsp[0].variable.floatVar != 0) {
			temp.intVar = 0;
			temp.floatVar = yyvsp[-2].variable.floatVar / yyvsp[0].variable.floatVar;
		}else {
			char *t = "Type mismatch";
			yyerror2(3,t, "");
		}
		
		yyval.variable = temp;
	  ;
    break;}
case 43:
#line 485 "compilerC.y"
{
		struct strVariable temp2;

		int flag;
		if(yyvsp[-2].variable.intVar != 0 && yyvsp[0].variable.intVar != 0) {
			temp2.floatVar = 0;
			temp2.intVar = yyvsp[-2].variable.intVar - yyvsp[0].variable.intVar;
		}else if(yyvsp[-2].variable.floatVar != 0 && yyvsp[0].variable.floatVar != 0) {
			temp2.intVar = 0;
			temp2.floatVar = yyvsp[-2].variable.floatVar - yyvsp[0].variable.floatVar;
		}else {
			char *t = "Type mismatch";
			yyerror2(3,t, "");
		}
		
		yyval.variable = temp2;

	  ;
    break;}
case 44:
#line 504 "compilerC.y"
{
		//$$ = $1 * $3;
		
		struct strVariable temp;

		int flag;
		if(yyvsp[-2].variable.intVar != 0 && yyvsp[0].variable.intVar != 0) {
			temp.floatVar = 0;
			temp.intVar = yyvsp[-2].variable.intVar * yyvsp[0].variable.intVar;
		}else if(yyvsp[-2].variable.floatVar != 0 && yyvsp[0].variable.floatVar != 0) {
			temp.intVar = 0;
			temp.floatVar = yyvsp[-2].variable.floatVar * yyvsp[0].variable.floatVar;
		}else {
			char *t = "Type mismatch";
			yyerror2(3,t, "");
		}
		
		yyval.variable = temp;
	  ;
    break;}
case 45:
#line 524 "compilerC.y"
{
		int flag;
		char *t;
	    flag = search(yyvsp[0].name);
		
		struct strVariable temp;

		if(flag == -1){
			t = "Identifier not defined - ";
			yyerror2(3,t, yyvsp[0].name);
		}else{
			if(tab[flag].type == 1){
				temp.intVar = atoi(tab[flag].value);
				temp.floatVar = 0;
			}
			else {
				temp.intVar = 0;
				temp.floatVar = atof(tab[flag].value);
			}
		}
		
		yyval.variable = temp;
	  ;
    break;}
case 47:
#line 552 "compilerC.y"
{
		yyval.variable = yyvsp[0].variable;
	;
    break;}
case 48:
#line 556 "compilerC.y"
{
		yyval.variable = yyvsp[0].variable;
	;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_name_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_name_LLOC.first_line;
      yylsp->first_column = YY_parser_name_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_name_NERRS;

#ifdef YY_parser_name_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_name_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_name_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_name_ERROR_VERBOSE */
	YY_parser_name_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_name_CHAR == YYEOF)
	YYABORT;

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_name_CHAR, yytname[yychar1]);
#endif

      YY_parser_name_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
  *++yylsp = YY_parser_name_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 563 "compilerC.y"



void valAssign(int modifier, char s1[], char s3[]){
	int flag,flag2 = 0;
	char temp[20];

	flag = search(s1);

	if(flag == -1){
		char *t ="Identifier Not present - ";
		yyerror2(3,t,s1);
	}else{
		switch(modifier){
			case 1:
				if(tab[flag].type == 1) flag2 = 1;
				break;

			case 2:
				if(tab[flag].type == 2) flag2 = 1;
				break;
			case 3:
				if(tab[flag].type == 3) flag2 = 1;
			;
		}
		if(flag2 == 1){
			insertVal(s3, flag);
		}else{
			char *t ="Wrong Type Error - ";
			yyerror2(3,t,s3);
		}
	}
}

int yyerror(char *s)
{
	printf("Syntax Error on line %d\n%s\n",linenum, s);
	return 0;
}

void yyerror2(int type, char *s, char b[])
{
	//todo change print to file
	switch(type){
		case 1:
			printf("Syntax Error on line - %d\n%s\n",linenum, s);
			break;
		case 2:
			printf("Lexical Error on line - %d: %s\n",linenum, s);
			break;
		case 3:
			printf("Line - %d: %s%s\n",linenum, s, b);
			break;
	}

	exit(0);
}

int search(char name[]){

	int i;
	int flag = -1;

	for(i = 0; i < ptr; i++){
		if(strcmp(tab[i].name, name) == 0){
			flag = i;
			break;
		}
	}

	return flag;

}

void insert(char name[], int type, char value[]){

	strcpy(tab[ptr].name, name);
	strcpy(tab[ptr].value, value);
	tab[ptr].type = type;

	ptr++;

	printTab();
}

void insertVal(char value[], int posi){

	strcpy(tab[posi].value, value);

	printTab();

}

void printTab(){

	int i;

	for(i = 0; i < ptr; i++){

	//use for testing
		/*printf("Name - %s, value - %s, type - ", tab[i].name, tab[i].value);
		if(tab[i].type == 1) printf("int\n");
		else if(tab[i].type == 2) printf("float\n");*/
	}
}

int main()
{
	//todo remove clear
    system("clear");
	extern FILE *yyin, *yyout; 
    char *file[] = {"testeIf.txt","testeFor.txt","testeProf.txt","testeWhile.txt","testeStruct.txt","testeInclude.txt","testeErrorId.txt","testeSytaxeError.txt"};
	
	int i=0;
	int op=-1;
	do{
	system("clear");
	for(i=0;i<8;i++){
		printf("Ficheiro %d - %s\n",i+1,file[i]);
	}
	printf("\nEscolha um ficheiro para abrir: ");
	scanf("%d",&op);
	}while (op>8 || op<0);
	
	op = op -1;
	system("clear");
	printf("Ficheiro numero %d aberto: %s \n\n",op+1,file[op]);
	
    yyin = fopen(file[op], "r"); 
	if( yyin == NULL) {
		fprintf(stderr,"Ficheiro não aberto");
		exit(1);
	}	
    yyparse();
	
	
	
    return 0;
}